### ISSUE TITLE
HTTP 403: Resource not accessible by integration

### ISSUE THREAD

**Issue by joepio** [taiki-e/create-gh-release-action#13] opened 2022-06-15 11:46 UTC
Hi there! I just got this error:

```
release not found
HTTP 403: Resource not accessible by integration (https://api.github.com/repos/atomicdata-dev/atomic-data-rust/releases)
Error: Command failed: bash --noprofile --norc /home/runner/work/_actions/taiki-e/create-gh-release-action/v1/main.sh
```

[Example action](https://github.com/atomicdata-dev/atomic-data-rust/runs/6897519533?check_suite_focus=true#step:3:10)

Not entirely sure what is causing it, but it probably has to do with github's permission system. Some reported that adding `permissions: write-all` to the action definition solves the problem. I'm trying that now. If that works, maybe it should be added to the docs.

**Comment by taiki-e** [comment] 2022-06-15 11:50
Duplicate of https://github.com/taiki-e/upload-rust-binary-action/issues/15

**Comment by taiki-e** [comment] 2022-06-15 11:52
Adding permissions field like https://github.com/taiki-e/upload-rust-binary-action/issues/15#issuecomment-1141252687 to example sounds good to me.

**Comment by joepio** [comment] 2022-06-15 11:58
Yup, it worked! Thanks for the quick reply. I think adding it to the docs is a fitting solution.

**Closed** 2022-06-15 12:02 UTC
Labels: question

**Comment by taiki-e** [comment] 2022-09-08 12:32
@lukasz90b FYI, for permissions field, it is already used in examples in readme: https://github.com/taiki-e/create-gh-release-action/commit/0015858ce7b2c651ce5d75230e55d1a424848d48
